import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-indigo-50">
        <header className="w-full flex justify-center">
          <Header />
        </header>
        {children}
        <footer className="w-full ">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
